name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Build
        run: cargo build --release

      - name: Archive Binary
        run: tar -czvf arrow.tar.gz -C target/release arrow

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: arrow.tar.gz
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
