name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install musl tools
        run: sudo apt update && sudo apt install -y musl-tools

      - name: Add musl target
        run: rustup target add x86_64-unknown-linux-musl

      - name: Build Static Binary
        run: cargo build --release --target x86_64-unknown-linux-musl

      - name: Strip Binary
        run: strip target/x86_64-unknown-linux-musl/release/arrow

      - name: Archive Static Binary
        run: tar -czvf arrow.tar.gz -C target/x86_64-unknown-linux-musl/release arrow

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: arrow.tar.gz
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
